name: Download NY Snapshot & Deploy

on:
  workflow_dispatch:
  schedule:
    # Weekly on Monday at 2 AM UTC
    - cron: '0 2 * * 1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup wget
        run: sudo apt-get update && sudo apt-get install -y wget

      - name: Download New York section
        run: |
          chmod +x ./download_ny.sh
          ./download_ny.sh

      - name: Run link cleanup
        run: |
          chmod +x ./link_cleanup_script.sh
          ./link_cleanup_script.sh

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./permittestpractice_ny
